server {
    listen 80;
    server_name unicasoluciones.ar www.unicasoluciones.ar; # <- Cambiar por el dominio final o IP

    # Redirección de HTTP a HTTPS si configuras el certificado más adelante con Certbot
    # return 301 https://$host$request_uri;

    root /usr/share/nginx/html;
    index index.html;

    # Habilita compresión GZIP
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché de archivos estáticos (imágenes, CSS, JS) para acelerar la carga de la landing
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
